/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emailapp;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class readAndSend extends javax.swing.JFrame {

    /**
     * Creates new form readAndSend
     */
    public readAndSend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        texfiel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mesajalanı = new javax.swing.JTextArea();
        mailgonder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pane = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rast = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rast_button = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        too = new javax.swing.JTextField();
        e_imza_gonder = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textbox = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        panek = new javax.swing.JTextPane();
        emailgoster = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texfiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfielActionPerformed(evt);
            }
        });

        mesajalanı.setColumns(20);
        mesajalanı.setRows(5);
        jScrollPane1.setViewportView(mesajalanı);

        mailgonder.setText("GÖNDER");
        mailgonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailgonderActionPerformed(evt);
            }
        });

        jLabel2.setText("mesaj");

        jLabel3.setText("Mail adresi");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(texfiel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(mailgonder))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texfiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(mailgonder)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jLabel1.setText("Son gelen mail görüntüle ");

        jScrollPane2.setViewportView(pane);

        jButton1.setText("GÖSTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );

        jTabbedPane1.addTab("ŞifreliMail Gönderme", jPanel5);

        rast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rastActionPerformed(evt);
            }
        });

        jLabel4.setText("Mail göndermek istediğiniz adresi girin");

        rast_button.setText("Gönder");
        rast_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rast_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rast_button)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rast, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rast_button)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RASTGELE MAİL GÖNDERME", jPanel3);

        jLabel5.setText("Alıcı Mail Adresi");

        jLabel6.setText("Mesaj");

        too.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tooActionPerformed(evt);
            }
        });

        e_imza_gonder.setText("Gönder");
        e_imza_gonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_imza_gonderActionPerformed(evt);
            }
        });

        textbox.setColumns(20);
        textbox.setRows(5);
        jScrollPane3.setViewportView(textbox);

        jScrollPane4.setViewportView(panek);

        emailgoster.setText("Göster");
        emailgoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailgosterActionPerformed(evt);
            }
        });

        jLabel7.setText("Gelen Son Mesajı Görüntüle");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(too, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(e_imza_gonder)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(36, 36, 36)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(emailgoster)
                        .addGap(67, 67, 67))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(too, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(e_imza_gonder)
                    .addComponent(emailgoster))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("E-imza ile Gönderme", jPanel7);

        jLabel8.setText("Mail Adresi");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gönder");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Gizlemek İstediğiniz Mesaj");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        jLabel10.setText("Son Gelen Şifreli Mesaj ");

        jScrollPane6.setViewportView(jTextPane1);

        jButton3.setText("Göster");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Görsel URL");

        jLabel12.setText("Görsel width - highed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(60, 60, 60))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jTextField4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34))))
        );

        jTabbedPane1.addTab("Görseli Maill", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texfielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfielActionPerformed

    }//GEN-LAST:event_texfielActionPerformed
    String sahip; 
    private void mailgonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailgonderActionPerformed
        Connection conn=null;
        cyripto c = new cyripto();
        String to = texfiel.getText();
        String mesaj= mesajalanı.getText();
        String temp = null;
        byte[] read=null;
        try {

            String url = "jdbc:sqlite:C:/sqlite/db/mailAPP.db";
            conn = DriverManager.getConnection(url);
            String sqlkey = "SELECT * FROM keyTable where mail ='"+to+"';";
             PreparedStatement pst = conn.prepareStatement(sqlkey);
            ResultSet rss = pst.executeQuery();

            try {
                while(rss.next())
                {
                    String key = rss.getString("key");//read in database
                    System.out.println(key);
                    read = c.encrypt(mesaj,key);//encyription
                }

            } catch (Exception ex) {
                Logger.getLogger(readAndSend.class.getName()).log(Level.SEVERE, null, ex);
            }
            rss.close();
            pst.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(readAndSend.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        try {

            String mesaj2 = Base64.getEncoder().encodeToString(read);//byte[] to string
            hashing hs = new hashing();
            temp = hs.hash(mesaj); //hashing message
            String url = "jdbc:sqlite:C:/sqlite/db/mailAPP.db";

            conn = DriverManager.getConnection(url);

            String sql = "INSERT INTO sendbox (alıcı,gönderici,message,hash) VALUES(?,?,?,?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, to);
            pstmt.setString(2, sahip);
            pstmt.setString(3, mesaj2);
            pstmt.setString(4, temp);
            pstmt.executeUpdate();
            System.out.println("ekleme başarılı");
            JOptionPane.showMessageDialog(this, "Mail gönderildi");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mailgonderActionPerformed

    private void rastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rastActionPerformed

    private void rast_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rast_buttonActionPerformed
        Connection conn=null;
        cyripto c = new cyripto();
        hashing hs = new hashing();
        Random r=new Random();
        String mailAdress = rast.getText(); 
        String hashingMessage = null;
        String message=null;
        byte[] temp=null;
        String[] arr ={ "Consider","yourself","ae","task","Ii","have","ended","Our","relationship","ap","404",
            "not","found","Our","connection","now","disconnected","You","a","files","broken",
            "link","I","wish","I","had","been","forbidden","to","visit","an","threat","I","did",
            "not","initially","detect","You","became","a","virus","in","my","system","and","I",
            "had","to","Malware","you","out","of","it","Ik","have","now","completed","the",
            "uninstallation","process","have","reset","my","lifes","device","back","to",
            "its","original","settings","from","before","five","years","ago","when","I",
            "mistakenly","trusted","your","download","of","lies","So","good","luck",
            "spamming","your","way","into","someone","elses","unregistered","trust",
            "have","already","reported","your","corrupted","files"};

        for(int i=0;i<20;i++) message = message+ " " + arr[r.nextInt(99)]; // create random message

        try {

            String url = "jdbc:sqlite:C:/sqlite/db/mailAPP.db";
            conn = DriverManager.getConnection(url);
            String sqlkey = "SELECT * FROM keyTable where mail ='"+mailAdress+"';";
            PreparedStatement pst = conn.prepareStatement(sqlkey);
            ResultSet rss = pst.executeQuery();

            try {
                while(rss.next())
                {
                    String key = rss.getString("key");
                    System.out.println(key);
                    temp = c.encrypt(message,key);//encryipt random message
                }

            } catch (Exception ex) {
                Logger.getLogger(readAndSend.class.getName()).log(Level.SEVERE, null, ex);
            }
            rss.close();
            pst.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }

        try {

            String mesaj2 = Base64.getEncoder().encodeToString(temp);
            hashingMessage = hs.hash(message);//hasging ramdom message
            String url = "jdbc:sqlite:C:/sqlite/db/mailAPP.db";
            conn = DriverManager.getConnection(url);
            String sql = "INSERT INTO sendbox (alıcı,gönderici,message,hash) VALUES(?,?,?,?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, mailAdress);
            pstmt.setString(2, sahip);
            pstmt.setString(3, mesaj2);
            pstmt.setString(4, hashingMessage);
            pstmt.executeUpdate();
            System.out.println("ekleme başarılı");
            JOptionPane.showMessageDialog(this, "Mail gönderildi");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_rast_buttonActionPerformed

    private void e_imza_gonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_imza_gonderActionPerformed
        Connection conn=null;
        String to = too.getText();
        String text= textbox.getText();
        hashing h = new hashing();
        String hash = h.hash(text);// message hashing
        try {
            String url = "jdbc:sqlite:C:/sqlite/db/mailAPP.db";
            conn = DriverManager.getConnection(url);
            String sql = "INSERT INTO eImza (alici,mail,cyript,openKey,modNumber) VALUES(?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            RSA rsa = new RSA(); //create RSA and assign parameter
            BigInteger e = rsa.e;
            BigInteger d = rsa.d;
            BigInteger N = rsa.N;
            byte[] bytes = Base64.getDecoder().decode(hash);//hash convert to byte
            byte[] encrypted = rsa.encrypt(bytes); //RSA encryppted
            String cryp = Base64.getEncoder().encodeToString(encrypted); //crypted byte to string
            pst.setString(1, to);
            pst.setString(2,text); 
            pst.setString(3, cryp); 
            pst.setObject(4, e);
            pst.setObject(5, N);
            pst.executeUpdate();
            System.out.println("ekleme başarılı");
            JOptionPane.showMessageDialog(this, "Mail gönderildi");
            pst.close();
        }
        catch (SQLException e) {
            System.out.println(e.getMessage());
    }//GEN-LAST:event_e_imza_gonderActionPerformed
    }
    private void emailgosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailgosterActionPerformed

        Connection conn = null;
        String message = null;
        String eImza = null;
        String decrypted;
        hashing hs =new hashing();
        RSA rsa = new RSA(); 
        
        try {
            int a = 0, c=0 ;
            
            String url = "jdbc:sqlite:C:/sqlite/db/mailAPP.db";
            conn = DriverManager.getConnection(url);
            String sql = "SELECT * FROM eImza where alici ='"+sahip+"';";
            PreparedStatement psmt = conn.prepareStatement(sql);
            ResultSet rs = psmt.executeQuery();
            while(rs.next())
            {
                message = rs.getString("mail"); //read parameter in DB
                eImza = rs.getString("cyript");
                a = (int) rs.getObject("openKey"); 
               c = (int) rs.getObject("modNumber");
            }
             BigInteger key = BigInteger.valueOf(a);//parameter int to BigInteger
             BigInteger modN = BigInteger.valueOf(c);
            rs.close();
            psmt.close();
            byte[] b = Base64.getDecoder().decode(eImza); 
            
        byte[]array;
        array = rsa.decrypt(b, key, modN); // decrypted
        decrypted = Base64.getEncoder().encodeToString(array);
        String hass;
        hass = hs.hash(message);// text to hashing
       
      
            panek.setText(message); 
            JOptionPane.showMessageDialog(this, "alınan mesaj özeti doğru herhengi bir değişime uğramamıştır");
        
        
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
     
    }//GEN-LAST:event_emailgosterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        anaMenu aa = new anaMenu();
        cyripto cr= new cyripto();
        Connection conn = null;
        String message = null;
        String sent = null;
        String key = null;
        String hashed = null;
        hashing hs =new hashing();
        try {

            String url = "jdbc:sqlite:C:/sqlite/db/mailAPP.db";
            conn = DriverManager.getConnection(url);
            String sql = "SELECT * FROM sendbox where alıcı ='"+sahip+"';"; 
            PreparedStatement psmt = conn.prepareStatement(sql);
            ResultSet rs = psmt.executeQuery();
            while(rs.next())
            {
                message = rs.getString("message"); //read message and hashed in DB
                hashed = rs.getString("hash");
            }
            rs.close();
            psmt.close();
            String sqlkey = "SELECT * FROM keyTable where mail ='"+sahip+"';";
            PreparedStatement pst = conn.prepareStatement(sqlkey);
            ResultSet rss = pst.executeQuery();

            while(rss.next())
            {
                key = rss.getString("key"); //read key in DB
            }
            rss.close();
            pst.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }

        String decrypted = null;
        String has = null;
        try {
            byte[] bytes = Base64.getDecoder().decode(message); //String to byte []

            decrypted = cr.decrypt(bytes, key); //message decrypting

            has = hs.hash(decrypted); // hashing  decrypted
            System.out.println(has);
        } catch (Exception ex) {
            Logger.getLogger(readAndSend.class.getName()).log(Level.SEVERE, null, ex);
        }
        pane.setText(decrypted);

        if(hashed.equals(has)){ //control hasheds 
            JOptionPane.showMessageDialog(this, "alınan mesaj özeti doğru herhengi bir değişime uğramamıştır");
        }
        else{
            JOptionPane.showMessageDialog(this, "alınan mesaj hatalı olarak gelmiştir!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tooActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String secretMessage = jTextArea1.getText();
        String to = jTextField1.getText();
        String url= jTextField2.getText();
        String urlNew= url+ ".png";
        int width = jTextField3.getX();
        int highed = jTextField4.getX();
        watermark wtm = new watermark();
        File sourceImageFile = new File(url); //read İamge
        File destImageFile = new File(urlNew);//write image
        Connection conn=null;
         byte[] read=null;
        cyripto c = new cyripto();
     

            String URL = "jdbc:sqlite:C:/sqlite/db/mailAPP.db";
        try {
            conn = DriverManager.getConnection(URL);
        
            String sqlkey = "SELECT * FROM keyTable where mail ='"+to+"';";
            PreparedStatement pst;        
            pst = conn.prepareStatement(sqlkey);       
            ResultSet rss = pst.executeQuery();
            try {
                while(rss.next())
                {
                    String key = rss.getString("key");//read in database
                    read = c.encrypt(secretMessage,key);//encyription
                }
            } catch (Exception ex) {
                Logger.getLogger(readAndSend.class.getName()).log(Level.SEVERE, null, ex);
            
            }
            rss.close();
            pst.close();
            } catch (SQLException ex) {
            Logger.getLogger(readAndSend.class.getName()).log(Level.SEVERE, null, ex);
        }
        Steganography st = new Steganography();    
        String mesage = Base64.getEncoder().encodeToString(read);    
        wtm.addTextWatermark(mesage, sourceImageFile, destImageFile);//watermark method
        File f  = new File(urlNew);
        BufferedImage img = null;
        try {
            img = ImageIO.read(f);
        } catch (IOException ex) {
            Logger.getLogger(readAndSend.class.getName()).log(Level.SEVERE, null, ex);
        }
               
        BufferedImage bufferedImage = new BufferedImage(width,highed, BufferedImage.TYPE_INT_BGR);
        String str=null;
        st.encode(img, bufferedImage, width, highed, mesage,urlNew);// image steganography method
        
        try {
            conn = DriverManager.getConnection(URL);
            String sql = "INSERT INTO gorselMail (alıcı,resimyolu,width,highed) VALUES(?,?,?,?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, to);
            pstmt.setString(2, urlNew);
            pstmt.setInt(3, width);
            pstmt.setInt(4, highed);
            pstmt.executeUpdate();
            System.out.println("ekleme başarılı");
            pstmt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
        Connection conn = null;
        String URL = null;
        String key = null;
        int width = 0 ;
        int highed = 0 ;
        try {

            String url = "jdbc:sqlite:C:/sqlite/db/mailAPP.db";
            conn = DriverManager.getConnection(url);
            String sql = "SELECT * FROM gorselMail where alıcı ='"+sahip+"';"; 
            PreparedStatement psmt = conn.prepareStatement(sql);
            ResultSet rs = psmt.executeQuery();
            while(rs.next())
            {
                URL = rs.getString("resimyolu"); //read message and hashed in DB
                width=rs.getInt("width");
                highed=rs.getInt("highed");
            }
            rs.close();
            psmt.close();
            String sqlkey = "SELECT * FROM keyTable where mail ='"+sahip+"';";
            PreparedStatement pst = conn.prepareStatement(sqlkey);
            ResultSet rss = pst.executeQuery();

            while(rss.next())
            {
                key = rss.getString("key"); //read key in DB
            }
            rss.close();
            pst.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        if(key!=null){     
        File f = new File(URL);
        BufferedImage imga = null;
                try {
                    imga = ImageIO.read(f);
                } catch (IOException e) {
                }
        Steganography st= new Steganography();        
        String message =  st.decode(imga, width,highed);
        cyripto cr= new cyripto();
        String decrypted = null;
        
             = Base64.getDecoder().decode(message); //String to byte []
            try {
                
              decrypted = cr.decrypt(bytes, key); //message decrypting
              jTextPane1.setText(decrypted);
            } catch (Exception ex) {
                Logger.getLogger(readAndSend.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        

            JOptionPane.showMessageDialog(this, "Fotoğrafta gizlenen mesaj ekrana basılmıştır!");
        }
        else{
            JOptionPane.showMessageDialog(this, "Gelen mesajın anahtarı bilinmemektedir!");
        
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(readAndSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(readAndSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(readAndSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(readAndSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new readAndSend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton e_imza_gonder;
    private javax.swing.JButton emailgoster;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton mailgonder;
    private javax.swing.JTextArea mesajalanı;
    private javax.swing.JTextPane pane;
    private javax.swing.JTextPane panek;
    private javax.swing.JTextField rast;
    private javax.swing.JButton rast_button;
    private javax.swing.JTextField texfiel;
    private javax.swing.JTextArea textbox;
    private javax.swing.JTextField too;
    // End of variables declaration//GEN-END:variables
}
